### ISSUE TITLE
Raw list of Clojure inspired or related languages/libraries

### ISSUE THREAD

**Issue by kanaka** [chr15m/awesome-clojure-likes#2]
I might turn this into a PR if I find time, but a few others come to mind:

Here are some that are definitely worth mentioning:

- Lux: https://github.com/LuxLang/lux (syntax and overall look and feel from Clojure)
- Apricot: https://github.com/apricot-lang/apricot (Clojure-like Lisp on Rubinius)
- TimL: https://github.com/tpope/timl (Clojure like language which compiles down to VimL)
- Ki: https://github.com/lantiga/ki (Clojure data structures and semantics)
- Toccata: https://github.com/jduey/toccata (Clojure-inspired Lisp dialect that compiles to native using Clang)
- Slisp: https://github.com/bailesofhey/slisp (Modern Lisp variant inspired by Python, Clojure & Arc)
- Elixir: not a Lisp but clear lineage to Clojure:  https://elixirforum.com/t/elixir-features-inspired-or-modelled-after-other-languages/1842
- Carbonate: https://github.com/7even/carbonate (Clojure-inspired Lisp that compiles to Ruby)

There are also a bunch of other languages that haven't seen much activity lately:

- Gamelisp: https://github.com/Bunkerbewohner/gamelisp (game-oriented programming language inspired by Lisp, Go, Python, Clojure)
- ClojureC: https://github.com/schani/clojurec (Clojure to C compiler)
- Rouge: https://github.com/ecmendenhall/rouge (Ruby + Clojure)
- Gershwin: https://github.com/gershwin/gershwin (fusion of Clojure and Factor ideas)
- dcpu-lisp: https://github.com/hippiehunter/dcpu-lisp (Clojure like lisp for the DCPU16)
- fclojure: https://github.com/alandipert/fclojure (Minimal Clojure-like interpreter with FEXPRs)
- CljPerl: https://github.com/wehu/CljPerl (Clojure + Perl)
- clojure-py: https://github.com/drewr/clojure-py (implementation of Clojure in pure Python)
- las3r: https://github.com/aemoncannon/las3r (Clojure syntax lisp compiler for the AVM2)

Adoption of Clojure ideas in other languages:

- Functional Ruby: https://github.com/jdantonio/functional-ruby (Inspired by Erlang, Clojure, Haskell, and Functional Java)
- Endure: https://github.com/yupferris/Endure (persistent data structure library for C++11 inspired by (and often baked from) Clojure)
- rackjure: https://github.com/greghendershott/rackjure (add some Clojureness to Racket)
- vervel: https://github.com/blackwood/vervel (functional PHP utility methods inspired by Clojure and other functional langs/libs)
- guile-borrow: https://github.com/pasoev/guile-borrow (Racket and Clojure inspired language constructs in Gnu Guile)
- clojR: https://github.com/alekrutkowski/clojR (Clojure-inspired functions (macros) in R)
- Arkham: https://github.com/hiredman/Arkham (lisp interpreter with clojure like semantics)

Some more esoteric things:

- Swearjure: https://github.com/hyPiRion/swearjure (Turing complete Clojure subset, which prohibits alphanumeric characters)

Other misc: https://github.com/pragmatrix/matter, https://github.com/mlanza/cloe, https://github.com/edw/skim, https://github.com/anacrolix/gasp, https://github.com/miviwi/glang, https://github.com/adamrmoss/Lithp, https://github.com/nicl/functional-php, https://github.com/maxcountryman/mage, https://github.com/nelsonsar/pojure, https://github.com/jedrz/slisp, https://github.com/EasonLiao/gofp, https://github.com/marad/eljure

**Comment by chr15m** [comment]
@kanaka this is epic, thanks. Will take me a while to go through these.

**Comment by chr15m** [comment]
@kanaka have added these, thanks!

**Comment by rajkrish** [comment]
Please add Janet (if not in the list already) - 
https://janet-lang.org/

**Comment by chr15m** [comment]
@rajkrish will merge a PR for this!

[How to contribute](https://github.com/chr15m/awesome-clojure-likes/blob/master/contributing.md).
